# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile

before_install:
- gem update cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail
- xcodebuild -workspace Example/AGCircularPicker.xcworkspace -scheme AGCircularPicker-Example -destination "OS=10.3.1,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
- pod lib lint
